### ISSUE TITLE
InstructionReport.merge method needs adjustments

### ISSUE THREAD

**Issue by mjedynak** [lizardev/xquery-saxon#21]
object's address should not be taken into equality comparison

 Q{aaa:/path/module.xq}name($param, ``com.saxonica.functions.hof.CallableFunctionItem@6bee793f)`` <> Q{aaa:/path/module.xq}name($param, ``com.saxonica.functions.hof.CallableFunctionItem@7942a854)``

**Comment by mjedynak** [comment]
still fails for:
if (Q{xxx:/path/Module.xq}function($param)) then (FixedElement(Block(Q{xxx:/path/Module.xq}function($param), ValueOf(""), Q{xxx:/path/Module.xq}function($param), ValueOf(""), Q{xxx:/path/Module.xq}function($param), ValueOf(""), Q{xxx:/path/Module.xq}function($param), Q{xxx:/path/Module.xq}function($param)))) else if (true()) then (())
<>
if (Q{xxx:/path/Module.xq}function($param)) then (FixedElement(Block(Q{xxx:/path/Module.xq}function($param), ValueOf(""), Q{xxx:/path/Module.xq}function($param), ValueOf(""), Q{xxx:/path/Module.xq}function($param), ValueOf(""), Q{xxx:/path/Module.xq}function($param), ValueOf(""), Q{xxx:/path/Module.xq}function($param)))) else if (true()) then (())

**Comment by alaczynski** [comment]
Could you provide XQuery code for this instructions?

**Comment by alaczynski** [comment]
The issue is related to zero-length text node added during parsing in `net.sf.saxon.query.QueryParser#readElementContent` (line 4113).
We have observed that this instruction could be omitted in some compilations but we do not know the root cause yet.
As temporary fix this instruction will be removed from string representation of instruction.
Below example code with zero-length text node:
``` xquery
<a>
    {fun1()}
    {fun2()}
</a>
```
